# Generated by Django 4.1.2 on 2023-01-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_listing_category_closed_listing"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_closed",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name="Closed_listing",
        ),
    ]
